import React, { useState, useEffect } from "react";
import Modal from "./Modal";
import Button from "./Button";
import { InputField } from "./Card";
import styles from "./UploadModal.module.css";
import { Paperclip, X } from "lucide-react";
// Import form handling libraries. react-hook-form handles state and validation without re-rendering the whole component on every keystroke.
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
// Import our custom validation rules from the utilities file to keep validation consistent across the app
import { dateRule, longTextRule } from "@/utils/validation";
// Import our custom hook that interacts with the backend for certificates
import { useCertificates } from "@/hooks/useCertificates";

// Define the validation schema for the Certificate Form using Yup.
// This ensures the user cannot submit the form if required fields are missing or invalid.
const schema = yup.object({
	name: longTextRule.required("Certificate name is required"),
	issueDate: dateRule.required("Issue date is required"),
	expiryDate: dateRule
		.required("Expiry date is required")
		.test(
			"is-after-issue", // Custom rule name
			"Expiry date must be after issue date", // Error message shown to the user
			function (value) {
				const { issueDate } = this.parent;
				if (!issueDate || !value) return true
				return new Date(value) > new Date(issueDate);
			}
		),
	// Validate the file input. `yup.mixed()` is used because it's a FileList object, not a simple string or number.
	file: yup.mixed()
		.test("required", "Please upload a document", (value) => {
			// Ensure that a file has actually been selected (FileList has a length > 0)
			return value && value.length > 0;
		})
		.test("fileSize", "File size is too large (max 5MB)", (value) => {
			if (!value || value.length === 0) return true;
			return value[0].size <= 5 * 1024 * 1024; // 5MB limit
		})
		.test("fileType", "Unsupported file type. Use PDF, JPG, or PNG.", (value) => {
			if (!value || value.length === 0) return true;
			const allowedTypes = ['application/pdf', 'image/jpeg', 'image/jpg', 'image/png'];
			return allowedTypes.includes(value[0].type);
		})
});

/**
 * Reusable Certificate Upload Modal Component.
 * @param {boolean} isOpen - Determines if the modal should be visible.
 * @param {function} onClose - Function to call when the modal is closed (e.g., when clicking "Cancel").
 * @param {string} userId - The ID of the user (Caregiver) this certificate belongs to.
 * @param {function} onSuccess - Optional callback executed after a successful upload.
 */
export default function CertificateModal({ isOpen, onClose, userId, onSuccess }) {
	// Destructure the upload mutation from our custom hook. 
	// `uploadCertificate` is the function we call to start the API request.
	// `isCertificateUploading` is a boolean that is true while the request is in progress.
	const { uploadCertificate, isCertificateUploading, isCertificateError, certificateErrorMessage } = useCertificates(userId);

	// Initialize react-hook-form.
	// `register` connects input elements to the form state.
	// `handleSubmit` wraps our custom save function and runs validation first.
	// `watch` lets us look at the current value of a specific input.
	// `setValue` allows us to manually update the form state (e.g., clearing the file input).
	// `control` is used for custom inputs that need more complex integration.
	// `errors` contains all the validation error messages generated by our Yup schema.
	// `reset` clears all inputs back to their default empty states.
	const { register, handleSubmit, watch, setValue, control, formState: { errors }, reset } = useForm({
		resolver: yupResolver(schema), // Connect the Yup validation schema to this form
	});

	// We "watch" the file input so we can dynamically display the selected file's name in the UI.
	const selectedFile = watch("file");

	// This effect runs whenever the modal opens or closes (`isOpen` changes).
	useEffect(() => {
		if (!isOpen) {
			// If the modal is closing, we clean up by resetting the form and clearing any old errors.
			// This ensures the modal is perfectly clean the next time it's opened.
			reset();
		}
	}, [isOpen, reset]);

	// This function is triggered when the user clicks "Save Certificate" AND the form passes all Yup validations.
	const handleSave = async (formData) => {

		// Call the mutation function from `useCertificates`, passing the validated form data.
		uploadCertificate(formData, {
			onSuccess: () => {
				// If the API call succeeds, trigger the parent component's onSuccess callback if one exists
				if (onSuccess) onSuccess();
				// Close the modal
				onClose();
				// Clear the form fields
				reset();
			}
		});
	};

	return (
		// The base Modal component handles the dark overlay and centering
		<Modal isOpen={isOpen} onClose={() => { onClose(); reset(); }}>
			<h2 style={{ marginBottom: '20px' }}>Add New Certificate</h2>

			{/* The form wraps all inputs. `handleSubmit` ensures `handleSave` only runs if validation passes. */}
			<form onSubmit={handleSubmit(handleSave)}>
				{/* The InputField component automatically renders the label and input, and handles error styling. */}
				<InputField label="Certificate Name" name="name" register={register} error={errors.name} />

				{/* Group the date fields side-by-side using CSS grid */}
				<div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
					<InputField label="Issue Date" type="date" name="issueDate" register={register} control={control} error={errors.issueDate} />
					<InputField label="Expiry Date" type="date" name="expiryDate" register={register} control={control} error={errors.expiryDate} />
				</div>

				{/* Custom UI for the File Upload Dropzone */}
				<div className={styles.uploadField}>
					<label className={styles.label}>Certificate Document</label>
					{/* Add a red border class to the dropzone if the file validation failed */}
					<div className={`${styles.dropzone} ${errors.file ? styles.errorBorder : ""}`}>
						{/* The actual HTML file input is hidden via CSS, but registered with react-hook-form */}
						<input
							type="file"
							id="certFile"
							{...register("file")}
							className={styles.hiddenInput}
						/>
						{/* Clicking this label triggers the hidden file input above, opening the OS file browser */}
						<label htmlFor="certFile" className={styles.uploadTrigger}>
							<Paperclip size={18} />
							{/* Display the selected file name if it exists, otherwise show default placeholder text */}
							<span>{selectedFile?.[0] ? selectedFile[0].name : "Click to select a file (PDF, JPG...)"}</span>

							{/* If a file is selected, render an 'X' button to let the user clear the selection */}
							{selectedFile?.[0] && (
								<X size={16} className={styles.clearFile} onClick={(e) => {
									e.preventDefault(); // Prevent the label click from opening the file browser again
									setValue("file", null); // Manually clear the file from react-hook-form state
								}} />
							)}
						</label>
					</div>
					{/* Render the Yup validation error message if the file is missing or invalid */}
					{errors.file && <p className={styles.errorMessage}>{errors.file.message}</p>}

					{/* Help text letting the user know the size and format limits */}
					<p className={styles.fileNote} style={{ marginTop: '0.5rem', textAlign: 'center' }}>
						Max 5MB. Supported formats: PDF, JPG, PNG.
					</p>
				</div>

				{/* Render any backend upload errors (e.g. file too large, server down) */}
				{isCertificateError && <p className={styles.errorMessage}>{certificateErrorMessage}</p>}

				{/* Footer section containing Cancel and Save buttons */}
				<div style={{ display: "flex", justifyContent: "flex-end", marginTop: 24, gap: 12 }}>
					<Button variant="secondary" type="button" onClick={() => { onClose(); reset(); }}>Cancel</Button>
					{/* Disable the submit button while an upload is in progress to prevent duplicate submissions */}
					<Button type="submit" disabled={isCertificateUploading}>
						{isCertificateUploading ? "Saving..." : "Save Certificate"}
					</Button>
				</div>
			</form>
		</Modal>
	);
}
